In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.5.1+cu118


# Introduction to Tensors

## Creating tensors


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2 ,3],
                       [2, 4, 6],
                       [3, 6, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 6, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> repeat`

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8934, 0.5179, 0.9297, 0.1358],
        [0.8164, 0.7717, 0.2145, 0.1547],
        [0.8781, 0.0370, 0.3582, 0.6417]])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range() and get deprecated message, use torch.arange() instead
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Use torch range( )
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into PyTorch & Deep Learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device (GPU/CPU)

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.type`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5856, 0.7380, 0.9200, 0.1975],
        [0.9974, 0.8479, 0.0704, 0.6756],
        [0.2993, 0.2329, 0.4977, 0.4078]])

In [32]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5856, 0.7380, 0.9200, 0.1975],
        [0.9974, 0.8479, 0.0704, 0.6756],
        [0.2993, 0.2329, 0.4977, 0.4078]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations )
Tensor operations include :
* Addition
* Subtraction
* Multiplication (element—wise)
* Division
* Matrix multiplication

In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor( [1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [36]:
# PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)

In [37]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f" Equals: {tensor * tensor}" )

tensor([1, 2, 3]) * tensor([1, 2, 3])
 Equals: tensor([1, 4, 9])


In [38]:
# Matrix wise multiplication
print(tensor, ".", tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3]) . tensor([1, 2, 3])


tensor(14)

In [39]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T) # Alias for matmul, also doing transpose of B

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [40]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
# Find the min
torch.min(x) # also x.min() will do the same

tensor(0)

In [42]:
# Find the max
torch.max(x) # also x.max() will do the same

tensor(90)

In [43]:
# Find the mean - note: the function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) # also x.mean() will do the same

tensor(45.)

In [44]:
# Find the sum
torch.sum(x) # also x.sum() will do

tensor(450)

### Finding positional min and max

In [45]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
x.argmin(), x.argmax() # returns the index of the min and max values

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing
* Reshaping — reshapes an input tensor to a defined shape
* View — Return a view Of an input tensor Of certain shape but keep the same memory as the original tensor
* Stacking — combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze — removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension from a tensor
* Permute — Return a view of the input with dimensions permuted (swapped) in a certain way

In [47]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# Add an extra dimension
x_reshaped = x.reshape (9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [49]:
# Add an extra dimension
x_reshaped = x.reshape (1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [51]:
# Changing z changes x  because a view of a tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [52]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [53]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped. shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze( )
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed. shape}")

Previous tensor: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
New shape: torch.Size([9])


In [54]:
# torch.unsqueeze() - adds a dimension to a target tensor at a specified dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New shape: torch.Size([1, 9])


In [55]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis or dim order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0 to 2, axis 1 to 0 and axis 2 to 1
print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # 3, 224, 224

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [56]:
# Create a tensor
import torch
x = torch. arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [61]:
# Let's index on the most inner bracker (dim=2)
x[0][2][2]

tensor(9)

In [62]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [63]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [64]:
# Get all values of 0th dimension but only index 1 of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [65]:
# Get index 0 of 0th and 1st dimensions but all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor-> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [1]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning:data type 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
# Change the value of array, what will this do to `tensor`?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [5]:
# Change the value of tensor, what will this do to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out Of random)

In short how a neural network learns:

`start with random numbers tensor operations update random numbers to try and
make them better representations Of the data again again again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed
Essentially what the random seed does is "flavour" the randomness

In [26]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3051, 0.4210, 0.2862, 0.8411],
        [0.6328, 0.0605, 0.6904, 0.1451],
        [0.0694, 0.8375, 0.2348, 0.5790]])
tensor([[0.1703, 0.4460, 0.2311, 0.1767],
        [0.0074, 0.3332, 0.9662, 0.7953],
        [0.3341, 0.6978, 0.4066, 0.8961]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [28]:
# Let s make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
